server:
  port: 8095

spring:
  datasource:
    platform: postgres
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    validationQuery: SELECT 1
    hikari:
      idle-timeout: 10000
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baselineOnMigrate: true
    locations: classpath:/db/migration

redis:
  host: ${REDISTOGO_URL:localhost}
  port: ${REDISTOGO_PORT:6379}
