server:
  port: 8096

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    validationQuery: SELECT 1
    hikari:
      idle-timeout: 10000
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    rabbitmq:
      host: localhost
      port: 5672
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    baselineOnMigrate: true
    locations: classpath:/db/migration

redis:
  uri: redis://dmy:dmy@localhost:6379/
  port: 6379
