server:
  port: 8095

spring:
  datasource:
    platform: postgres
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    validationQuery: SELECT 1
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    properties:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: ${POSTGRES_URI}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baselineOnMigrate: true
    locations: classpath:/db/migration

redis:
  host: ${REDISTOGO_URL:localhost}
  port: ${REDISTOGO_PORT:6379}
