server:
  port: 8095

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    validationQuery: SELECT 1
    hikari:
      idle-timeout: 10000
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    baselineOnMigrate: true
    locations: classpath:/db/migration

redis:
  uri: redis://dmy:dmy@localhost:6379/
  port: 6379
